export const SET_CHI_TIET_CONG_VIEC = 'SET_CHI_TIET_CONG_VIEC'
export const DSCV_THEO_TEN = 'DSCV_THEO_TEN'
export const LAY_TT_LOAI_CV_CHINH = 'LAY_TT_LOAI_CV_CHINH'
export const LAY_DSCV_THEO_CV_CHINH = 'LAY_DSCV_THEO_CV_CHINH'

